// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPConstants
{
        public const string achievement_bling = "CgkIxpXx0LYLEAIQAw"; // <GPGSID>
        public const string achievement_pirate_slayer = "CgkIxpXx0LYLEAIQCA"; // <GPGSID>
        public const string leaderboard_single_game_winnings = "CgkIxpXx0LYLEAIQBw"; // <GPGSID>
        public const string achievement_the_gates_to_the_universe = "CgkIxpXx0LYLEAIQBg"; // <GPGSID>
        public const string achievement_starfighter_ace = "CgkIxpXx0LYLEAIQCg"; // <GPGSID>
        public const string achievement_space_veteran = "CgkIxpXx0LYLEAIQCQ"; // <GPGSID>
        public const string achievement_dont_get_sucked_in = "CgkIxpXx0LYLEAIQBQ"; // <GPGSID>
        public const string achievement_phat_stax = "CgkIxpXx0LYLEAIQBA"; // <GPGSID>
        public const string achievement_it_takes_practice = "CgkIxpXx0LYLEAIQAg"; // <GPGSID>
        public const string leaderboard_single_game_score = "CgkIxpXx0LYLEAIQAQ"; // <GPGSID>

}

